package jq

// builtinDocs maps builtin names to one-line descriptions.
var builtinDocs = map[string]string{
	"select":        "Yield input if condition is truthy, otherwise produce no output",
	"empty":         "Produce no output",
	"error":         "Raise an error with the given message",
	"not":           "Boolean negation: true→false, false→true, null→true",
	"type":          "Return the type name: \"object\", \"array\", \"string\", \"number\", \"boolean\", \"null\"",
	"length":        "String length, array/object size, null→0, boolean→0, number→absolute value",
	"keys":          "Array of keys (sorted for objects, indices for arrays)",
	"values":        "Array of values from an object or array",
	"has":           "Test if object has a key or array has an index",
	"contains":      "Test if input contains the given value (recursive for objects/arrays)",
	"to_entries":    "Convert object to array of {key, value} pairs",
	"from_entries":  "Convert array of {key, value} pairs to object",
	"with_entries":  "Apply a filter to each {key, value} entry of an object",
	"test":          "Test if input string matches a regex (returns boolean)",
	"match":         "Match input string against a regex (returns match object)",
	"startswith":    "Test if string starts with the given prefix",
	"endswith":      "Test if string ends with the given suffix",
	"split":         "Split a string by separator into an array",
	"join":          "Join an array of strings with a separator",
	"ascii_downcase": "Convert string to lowercase",
	"ascii_upcase":  "Convert string to uppercase",
	"ltrimstr":      "Remove prefix from string if present",
	"rtrimstr":      "Remove suffix from string if present",
	"tostring":      "Convert value to its string representation",
	"tonumber":      "Convert string to number",
	"map":           "Apply a filter to each element of an array",
	"map_values":    "Apply a filter to each value of an object or array",
	"sort":          "Sort an array",
	"sort_by":       "Sort an array by the result of a filter",
	"reverse":       "Reverse an array or string",
	"group_by":      "Group array elements by the result of a filter",
	"unique":        "Remove duplicate elements from an array",
	"unique_by":     "Remove duplicates by comparing the result of a filter",
	"flatten":       "Flatten nested arrays",
	"first":         "Return the first element of an array",
	"last":          "Return the last element of an array",
	"range":         "Generate numbers in a range: range(n) or range(m; n)",
	"limit":         "Take at most n results from a generator",
	"add":           "Sum/concatenate all elements (numbers, strings, arrays, objects)",
	"any":           "Test if any element satisfies a condition",
	"all":           "Test if all elements satisfy a condition",
	"min":           "Minimum value in an array",
	"max":           "Maximum value in an array",
	"min_by":        "Minimum element by the result of a filter",
	"max_by":        "Maximum element by the result of a filter",
	"tojson":        "Serialize value to a JSON string",
	"fromjson":      "Parse a JSON string into a value",
	"abs":           "Absolute value of a number",
	"floor":         "Round down to nearest integer",
	"ceil":          "Round up to nearest integer",
	"round":         "Round to nearest integer",
	"recurse":       "Recursively apply a filter (default: recurse(.[]?))",
	"debug":         "Pass through value, printing it to stderr",
	"path":          "Output the path to elements matching a filter",
	"getpath":       "Get the value at a given path",
	"objects":       "Select only object values",
	"arrays":        "Select only array values",
	"strings":       "Select only string values",
	"numbers":       "Select only number values",
	"booleans":      "Select only boolean values",
	"nulls":         "Select only null values",
	"scalars":       "Select only scalar values (not objects or arrays)",
	"iterables":     "Select only iterable values (objects and arrays)",
	"if":            "Conditional: if COND then EXPR elif COND then EXPR else EXPR end",
	"reduce":        "Fold: reduce EXPR as $var (INIT; UPDATE)",
	"foreach":       "Iterate with state: foreach EXPR as $var (INIT; UPDATE; EXTRACT)",
	"try":           "Suppress errors: try EXPR catch HANDLER",
	"def":           "Define a function: def name(args): body;",
}

// BuiltinDoc returns the one-line documentation for a builtin, or "" if not found.
func BuiltinDoc(name string) string {
	return builtinDocs[name]
}
